from tkinter import *
root = Tk()
root.title("Colors")
#root.geometry('600x400')
frame=Frame(root)
frame.pack()
bottomframe=Frame(root)
bottomframe.pack(side="bottom")
greenbutt=Button(frame,text="Green",fg="green")
greenbutt.pack(side="left")
redbutt=Button(frame,text="Red",fg="red")
redbutt.pack(side="right")
bluebutt=Button(frame,text="Blue",fg="blue")
bluebutt.pack(side="bottom")
blackbutt=Button(bottomframe,text="Black",fg="black")
blackbutt.pack(side="top")
root.mainloop()